export const ACTION_TYPES = {
  // User Actions
  SET_USER: "USER/SET_USER",
  SET_USER_LOADING: "USER/SET_LOADING",
  SET_USER_ERROR: "USER/SET_ERROR",

  // Product Actions
  SET_PRODUCTS: "PRODUCTS/SET_PRODUCTS",
  SET_PRODUCTS_LOADING: "PRODUCTS/SET_LOADING",

  // Cart Actions
  ADD_TO_CART: "CART/ADD_TO_CART",
  UPDATE_CART: "CART/UPDATE_CART",
  CLEAR_CART: "CART/CLEAR_CART",

  // Products Actions
  SET_PRODUCTS: "PRODUCTS/SET_PRODUCTS",

  // Orders Actions
  SET_ORDERS: "ORDERS/SET_ORDERS",
  SET_ORDERS_LOADING: "ORDERS/SET_LOADING",
  SET_ORDERS_ERROR: "ORDERS/SET_ERROR",

  // UI Actions
  TOGGLE_CART: "UI/TOGGLE_CART",
  SET_AUTH_READY: "UI/SET_AUTH_READY",
  SET_GLOBAL_LOADING: "UI/SET_LOADING",
  SET_SEARCH_QUERY: "UI/SET_SEARCH_QUERY",
  PUSH_TOAST: "UI/PUSH_TOAST",
};
